package ae.uaepass.identity.entity;

public enum AuditEventType {
    REGISTRATION_START,
    REGISTRATION_COMPLETE,
    OTP_SENT,
    OTP_VERIFIED,
    OTP_FAILED,
    PIN_CREATED,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    TOKEN_ISSUED,
    TOKEN_REVOKED,
    TOKEN_REPLAYED,
    CONSENT_GRANTED,
    ACCOUNT_LOCKED,
    ACCOUNT_SUSPENDED,
    SESSION_REVOKED,
    DEVICE_REGISTERED,
    DEVICE_REVOKED,
    RISK_EVENT_CREATED,
    KEY_ROTATION_NEEDED,
    PIN_LOCKOUT,
    OTP_LOCKOUT
}

